@hostname = http://localhost:3333
@user_id_admin = fd751ec2-309f-447f-8eb6-ff95f4e3e2da
@user_id = a08b7f49-3182-4cec-a0a5-79c2462903fb

###

POST {{hostname}}/users
content-type: application/json
username: marcelo.mac

{
	"name": "João 3",
  "email": "joao6.a.mac@gmail.com",
  "admin": false
}

###

PATCH {{hostname}}/users/{{user_id_admin}}/admin
content-type: application/json


###

GET {{hostname}}/users/{{user_id}}
content-type: application/json

###

GET {{hostname}}/users
content-type: application/json
user_id: {{user_id_admin}} 
